services:
  - type: web
    name: sharepoint-list-manager
    env: static
    buildCommand: echo "Static site ready"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
