services:
  - type: web
    name: sharepoint-list-manager
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
